version: '3'

services:
  web:
    image: 'laravel-app'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8090:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stackoverflow
    ports:
      - '3307:3306'
